print ("Program starting.")
print ("Estimate how many minutes you spent on programming...\n")
Feed = input("A1_T1: ")
a1_t1 = int(Feed)
Feed = input("A1_T2: ")
a1_t2 = int(Feed)
Feed = input("A1_T3: ")
a1_t3 = int(Feed)
Feed = input("A1_T4: ")
a1_t4 = int(Feed)
Feed = input("A1_T5: ")
a1_t5 = int(Feed)
Feed = input("A1_T6: ")
a1_t6 = int(Feed)
Feed = input("A1_T7: ")
a1_t7 = int(Feed)
total = sum([a1_t1, a1_t2, a1_t3, a1_t4, a1_t5, a1_t6, a1_t7])
average = round(total / 7, 2)
print ()
print (f"In total you spent {total} minutes on programming.")
print (f"Average per task was {average} min and same rounded to the nearest integer {round(average)} min.\n")
print ("Program ending.")